-- local neogit = require('neogit')
--
-- neogit.setup {
--     integrations = {
--         diffview = true,
--     },
--     mappings = {
--         finder = {
--             ["<C-j>"] = "Next",
--             ["<C-k>"] = "Previous"
--         },
--         popup = {
--             ["F"] = "PullPopup",
--         }
--     }
-- }
--
-- vim.keymap.set('n', '<leader>gg', '<cmd>Neogit<cr>')
